use_frameworks!

platform :ios, '9.0'

target 'PLLoginComponent_Example' do
  pod 'PLLoginComponent', :path => '../'

  target 'PLLoginComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
