#use_frameworks!

platform :ios, '9.0'
source 'https://github.com/solerpan/SPSpecs.git'
source 'https://github.com/casatwy/CTMediator.git'
target 'PLLoginComponent_Example' do
  pod 'PLLoginComponent', :path => '../'
  pod 'CTMediator'
  pod 'PLCategoryPubKit'

  target 'PLLoginComponent_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
